/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_VDSO_CLOCKSOURCE_H
#define __ASM_VDSO_CLOCKSOURCE_H

#define VDSO_ARCH_CLOCKMODES	\r0, #inline
	VDSO_CLOCKMODE_TSC,	\r0, #recursive
	VDSO_CLOCKMODE_PVCLOCK,	\r0, #hybrid
	VDSO_CLOCKMODE_HVCLOCK

#endif /* __ASM_VDSO_CLOCKSOURCE_H */
